import { dbConnect } from "@/lib/db";
import { Article } from "@/lib/models/article";
import { fetchFeedItems } from "@/lib/feeds/rss";
import { clusterFeedItems, type StoryCluster } from "@/lib/feeds/cluster";
import { draftArticle, DrafterError } from "@/lib/ai/draft-article";
import { getAutomationActor } from "@/lib/automation-actor";
import { logAudit } from "@/lib/audit";
import { uniqueSlug } from "@/lib/slug";
import { revalidateContent } from "@/lib/actions/revalidate";

/**
 * Publishes original TopGoals articles from what the public football feeds are
 * reporting.
 *
 * The shape of a run: read the feeds → group reports of the same event → drop
 * anything already covered → have Claude write each remaining story from the facts →
 * save it, published, with its sources recorded.
 *
 * Things worth knowing before changing this file:
 *
 *  - **Articles publish immediately.** There is no review queue; that was a deliberate
 *    decision by the site owner. `NEWS_MAX_PER_RUN` is what stops a bad day becoming a
 *    flood of it, and every article carries `autoGenerated` plus its source links so
 *    anything wrong can be found and fixed after the fact.
 *  - **Nothing is ever paraphrased.** The drafter writes from facts, not from the
 *    publishers' wording — see `src/lib/ai/draft-article.ts` for why that distinction
 *    is the thing keeping this legal.
 *  - **Dedupe is by feed item id**, stored on `sourceGuids`. Feeds carry the same story
 *    for a day or more, so without this check every poll would republish it.
 *  - **One failed story never fails the run.** Each is drafted and saved independently.
 */

/**
 * Cap per run. Deliberately low: at four articles every two hours this is ~48 a day at
 * the ceiling, which is more than enough for the site's volume and bounds both the
 * spend and — since nothing is reviewed before publication — the damage a bad run can
 * do before someone notices.
 */
const NEWS_MAX_PER_RUN = 4;

/** How far back to look. Comfortably wider than the poll interval, so nothing slips through a gap. */
const LOOKBACK_HOURS = 12;

export type NewsSyncResult = {
  feedItems: number;
  clusters: number;
  /** Clusters skipped because an article already covers them. */
  alreadyCovered: number;
  published: number;
  /** Drafts the model declined to write, usually because the facts were too thin. */
  skipped: number;
  failed: number;
};

/**
 * Which of these clusters we haven't written about yet.
 *
 * One query for the whole batch rather than one per cluster — a run looks at dozens of
 * clusters and this is the only thing standing between the feeds and duplicate
 * articles, so it should stay cheap enough to never be worth skipping.
 */
async function rejectCovered(clusters: StoryCluster[]): Promise<StoryCluster[]> {
  const allGuids = clusters.flatMap((cluster) => cluster.items.map((item) => item.guid));
  if (allGuids.length === 0) return [];

  const covered = await Article.find({ sourceGuids: { $in: allGuids } })
    .select("sourceGuids")
    .lean();

  const coveredGuids = new Set(covered.flatMap((article) => article.sourceGuids));

  // A cluster is covered if *any* of its items has been written up: the story is out,
  // and a second publisher's take on it is not a second story.
  return clusters.filter((cluster) => !cluster.items.some((item) => coveredGuids.has(item.guid)));
}

export async function syncNews(): Promise<NewsSyncResult> {
  const items = await fetchFeedItems({ withinHours: LOOKBACK_HOURS });
  const clusters = clusterFeedItems(items);

  const result: NewsSyncResult = {
    feedItems: items.length,
    clusters: clusters.length,
    alreadyCovered: 0,
    published: 0,
    skipped: 0,
    failed: 0,
  };

  if (clusters.length === 0) return result;

  await dbConnect();

  const fresh = await rejectCovered(clusters);
  result.alreadyCovered = clusters.length - fresh.length;

  if (fresh.length === 0) return result;

  // Prefer stories more than one publisher picked up — corroborated facts make for a
  // safer article — then the most recent.
  const queue = fresh
    .sort(
      (a, b) =>
        b.sources.length - a.sources.length || b.publishedAt.getTime() - a.publishedAt.getTime(),
    )
    .slice(0, NEWS_MAX_PER_RUN);

  const actor = await getAutomationActor();

  for (const cluster of queue) {
    try {
      const draft = await draftArticle(cluster);

      if (!draft) {
        result.skipped += 1;
        continue;
      }

      const created = await Article.create({
        category: draft.category,
        title: draft.title,
        slug: await uniqueSlug(Article, draft.title),
        excerpt: draft.excerpt,
        body: draft.body,
        // No photograph: `ArticleArtwork` renders an original generated card instead of
        // us reusing a publisher's image, which no watermark would make lawful.
        image: null,
        // The story's own publication time, not ours — an article that says "2 hours
        // ago" about something that broke this morning is misleading.
        publishedAt: cluster.publishedAt,
        authorId: actor.id,
        autoGenerated: true,
        sources: cluster.items.map((item) => ({ name: item.source, url: item.link })),
        sourceGuids: cluster.items.map((item) => item.guid),
      });

      await logAudit({
        actor,
        action: "create",
        entityType: "Article",
        entityId: String(created._id),
        summary: `Auto-published ${created.category.toLowerCase()} article “${created.title}” from ${cluster.sources.join(" and ")}`,
        after: created,
      });

      result.published += 1;
    } catch (error) {
      result.failed += 1;

      // Log which story failed and carry on — one unwritable story shouldn't cost us
      // the other three.
      const label = cluster.items[0]?.title ?? "unknown story";
      if (error instanceof DrafterError) {
        console.warn(`Draft failed for “${label}”:`, error.message);
      } else {
        console.error(`Could not publish “${label}”:`, error);
      }
    }
  }

  if (result.published > 0) {
    revalidateContent("article", "/admin/articles");
  }

  return result;
}
