import mongoose, { Schema, type InferSchemaType, type Model } from "mongoose";
import { ARTICLE_CATEGORIES } from "@/lib/constants";

const mediaSchema = new Schema(
  {
    secureUrl: { type: String, required: true },
    publicId: { type: String, required: true },
  },
  { _id: false },
);

/**
 * A publisher whose reporting an article was written from.
 *
 * Readers can follow the story back to its source, and if a detail turns out to be
 * wrong we can tell where it came from.
 *
 * Empty on generated match reports: those are written from `football-data.org` match
 * data we already licence (see `src/lib/reports/`), so there is no third-party
 * reporting to attribute. Headlines taken from other publishers aren't articles at all
 * — they're link-outs, stored on the SourceLink model.
 */
const sourceSchema = new Schema(
  {
    name: { type: String, required: true },
    url: { type: String, required: true },
  },
  { _id: false },
);

const articleSchema = new Schema(
  {
    category: { type: String, enum: ARTICLE_CATEGORIES, required: true },
    title: { type: String, required: true, trim: true },
    slug: { type: String, required: true, unique: true, trim: true },
    excerpt: { type: String, required: true, trim: true },
    body: { type: String, required: true },
    image: { type: mediaSchema, default: null },
    publishedAt: { type: Date, required: true, default: Date.now },
    authorId: { type: Schema.Types.ObjectId, ref: "User", required: true },

    // Exactly one article may be featured — it drives the homepage hero.
    featured: { type: Boolean, default: false },
    heroEyebrow: { type: String, trim: true, default: null },
    heroHeadline: { type: String, trim: true, default: null },
    /** Substring of heroHeadline rendered in the gold accent colour. */
    heroHeadlineAccent: { type: String, trim: true, default: null },
    heroDescription: { type: String, trim: true, default: null },
    heroPrimaryCtaLabel: { type: String, trim: true, default: null },
    heroPrimaryCtaHref: { type: String, trim: true, default: null },
    heroSecondaryCtaLabel: { type: String, trim: true, default: null },
    heroSecondaryCtaHref: { type: String, trim: true, default: null },

    // ---- Provenance (automation) ----

    /**
     * True when the article was drafted by the news pipeline rather than written in
     * the CMS. Surfaced in the admin list so unreviewed output stays auditable, and
     * on the article page so readers aren't misled about who wrote it.
     */
    autoGenerated: { type: Boolean, default: false },
    /** Publishers whose reports the story was written from. Empty for CMS articles. */
    sources: { type: [sourceSchema], default: [] },
    /**
     * Feed item ids this article already covers.
     *
     * The dedupe key for the whole pipeline: a story sits in an RSS feed for a day or
     * two, and without this every poll would write it up again. An array because one
     * article is often written from several publishers' reports of the same event.
     */
    sourceGuids: { type: [String], default: [] },
  },
  { timestamps: true },
);

// The DB itself refuses a second featured article, so a racing double-submit
// can't produce two heroes even if application logic slips.
articleSchema.index(
  { featured: 1 },
  { unique: true, partialFilterExpression: { featured: true } },
);
articleSchema.index({ category: 1, publishedAt: -1 });
articleSchema.index({ publishedAt: -1 });
// Every automation run queries this to find which feed items it has already covered.
articleSchema.index({ sourceGuids: 1 });

export type ArticleDoc = InferSchemaType<typeof articleSchema>;

export const Article: Model<ArticleDoc> =
  (mongoose.models.Article as Model<ArticleDoc>) ??
  mongoose.model<ArticleDoc>("Article", articleSchema);
