import { dbConnect } from "@/lib/db";
import { Article } from "@/lib/models/article";
import { relativeTime } from "@/lib/format";
import type { ArticleCategory } from "@/lib/constants";

/**
 * Read helpers for the public site.
 *
 * Everything returns plain, serialisable objects with `id: string` rather than
 * Mongoose documents: ObjectIds and hydrated docs can't cross into a Client
 * Component, and keeping the mapping here means UI props stay decoupled from the
 * database shape.
 */

export type NewsCard = {
  id: string;
  slug: string;
  tag: ArticleCategory;
  title: string;
  excerpt: string;
  time: string;
  imageUrl: string | null;
};

export type HeroContent = {
  slug: string;
  eyebrow: string;
  headline: string;
  headlineAccent: string | null;
  description: string;
  primaryCta: { label: string; href: string };
  secondaryCta: { label: string; href: string };
  imageUrl: string | null;
};

export async function getFeaturedArticle(): Promise<HeroContent | null> {
  await dbConnect();

  const article = await Article.findOne({ featured: true }).lean();
  if (!article) return null;

  return {
    slug: article.slug,
    eyebrow: article.heroEyebrow ?? article.category,
    // The hero fields are required when featuring, but fall back to the article's
    // own copy so a hand-edited database row can't render a blank hero.
    headline: article.heroHeadline ?? article.title,
    headlineAccent: article.heroHeadlineAccent ?? null,
    description: article.heroDescription ?? article.excerpt,
    primaryCta: {
      label: article.heroPrimaryCtaLabel || "Read more",
      href: article.heroPrimaryCtaHref || `/articles/${article.slug}`,
    },
    secondaryCta: {
      label: article.heroSecondaryCtaLabel || "Latest news",
      href: article.heroSecondaryCtaHref || `/articles/${article.slug}`,
    },
    imageUrl: article.image?.secureUrl ?? null,
  };
}

function toNewsCard(article: {
  _id: unknown;
  slug: string;
  category: ArticleCategory;
  title: string;
  excerpt: string;
  publishedAt: Date;
  image?: { secureUrl: string } | null;
}): NewsCard {
  return {
    id: String(article._id),
    slug: article.slug,
    tag: article.category,
    title: article.title,
    excerpt: article.excerpt,
    time: relativeTime(article.publishedAt),
    imageUrl: article.image?.secureUrl ?? null,
  };
}

/** The "Right Now" teasers beside the hero — the newest stories that aren't the hero. */
export async function getHeroSideStories(limit = 2): Promise<NewsCard[]> {
  await dbConnect();

  const articles = await Article.find({ featured: { $ne: true } })
    .sort({ publishedAt: -1 })
    .limit(limit)
    .lean();

  return articles.map(toNewsCard);
}

export async function getLatestNews(limit = 4): Promise<NewsCard[]> {
  await dbConnect();

  const articles = await Article.find().sort({ publishedAt: -1 }).limit(limit).lean();
  return articles.map(toNewsCard);
}

export async function getArticlesByCategory(
  category: ArticleCategory,
  limit = 20,
): Promise<NewsCard[]> {
  await dbConnect();

  const articles = await Article.find({ category }).sort({ publishedAt: -1 }).limit(limit).lean();
  return articles.map(toNewsCard);
}

export type ArticleDetail = {
  id: string;
  slug: string;
  category: ArticleCategory;
  title: string;
  excerpt: string;
  /** Split into paragraphs so the page doesn't need to parse markup. */
  paragraphs: string[];
  time: string;
  publishedAt: string;
  imageUrl: string | null;
  /** True when the news pipeline wrote this rather than a person. Disclosed to readers. */
  autoGenerated: boolean;
  /** Publishers the story was reported from, so readers can follow it back. */
  sources: { name: string; url: string }[];
};

export async function getArticleBySlug(slug: string): Promise<ArticleDetail | null> {
  await dbConnect();

  const article = await Article.findOne({ slug }).lean();
  if (!article) return null;

  return {
    id: String(article._id),
    slug: article.slug,
    category: article.category,
    title: article.title,
    excerpt: article.excerpt,
    paragraphs: article.body
      .split(/\n\s*\n/)
      .map((paragraph) => paragraph.trim())
      .filter(Boolean),
    time: relativeTime(article.publishedAt),
    publishedAt: article.publishedAt.toISOString(),
    imageUrl: article.image?.secureUrl ?? null,
    autoGenerated: article.autoGenerated ?? false,
    sources: (article.sources ?? []).map((source) => ({
      name: source.name,
      url: source.url,
    })),
  };
}

/** Other recent stories, for the "read next" block under an article. */
export async function getRelatedArticles(
  excludeSlug: string,
  category: ArticleCategory,
  limit = 3,
): Promise<NewsCard[]> {
  await dbConnect();

  const sameCategory = await Article.find({ slug: { $ne: excludeSlug }, category })
    .sort({ publishedAt: -1 })
    .limit(limit)
    .lean();

  if (sameCategory.length >= limit) return sameCategory.map(toNewsCard);

  // Top up from any category so the block isn't half empty on a young site.
  const excludeSlugs = [excludeSlug, ...sameCategory.map((a) => a.slug)];
  const filler = await Article.find({ slug: { $nin: excludeSlugs } })
    .sort({ publishedAt: -1 })
    .limit(limit - sameCategory.length)
    .lean();

  return [...sameCategory, ...filler].map(toNewsCard);
}

/** All slugs, so the article routes can be prerendered at build time. */
export async function getAllArticleSlugs(): Promise<string[]> {
  await dbConnect();

  const articles = await Article.find().select("slug").lean();
  return articles.map((article) => article.slug);
}
